use_frameworks!
source 'https://github.com/anan131435/KitBaseRepo.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_modular_headers!

target 'KitMainUI_Example' do
  pod 'KitMainUI', :path => '../'
  pod 'SVProgressHUD'
  pod 'KitBase', '1.2'
  pod 'Alamofire'
  pod 'SnapKit', '~> 5.0.0'
  target 'KitMainUI_Tests' do
    inherit! :search_paths

    
  end
end
